graph:
  yarn graphqelm $API_HOST/graphql --base Api

build:
  yarn ts-node ./node_modules/.bin/webpack --config webpack.dev.ts --reporter basic

watch:
  yarn ts-node ./node_modules/.bin/webpack --config webpack.dev.ts --watch

build-prod:
  yarn ts-node ./node_modules/.bin/webpack --config webpack.prod.ts

start:
  yarn ts-node ./node_modules/.bin/webpack-serve ./webpack.dev.ts

open-stats:
  yarn webpack-bundle-analyzer dist/app/stats.json
