build:
  elm make ./src/SignIn.elm ./src/SignUp.elm ./src/Admin.elm ./src/Investor.elm --output=src/elm-out/app.js

bundle:
  yarn ts-node ./node_modules/.bin/webpack --reporter basic

start:
  yarn ts-node ./node_modules/.bin/webpack-serve ./webpack.config.ts
