graph:
	just graph-app
	just graph-pub

graph-app:
	yarn elm-graphql $API_HOST/graphql-app --base Api \
		--header "Authorization: Bearer $SYSTEM_JWT"

graph-pub:
	yarn elm-graphql $API_HOST/graphql-pub --base ApiPub

test:
	yarn elm-test

build:
	yarn ts-node ./node_modules/.bin/webpack --config webpack.dev.ts --reporter basic

watch:
	yarn ts-node ./node_modules/.bin/webpack --config webpack.dev.ts

build-prod:
	NODE_ENV=production yarn ts-node ./node_modules/.bin/webpack --config webpack.prod.ts

start:
	yarn webpack-dev-server --config ./webpack.dev.js

open-stats:
	yarn webpack-bundle-analyzer dist/app/stats.json



