graph:
	just graph-app
	just graph-pub

graph-app:
	yarn elm-graphql $API_HOST/graphql-app --base Api \
		--header "Authorization: Bearer $SYSTEM_JWT"

graph-pub:
	yarn elm-graphql $API_HOST/graphql-pub --base ApiPub

elm-analyse:
	yarn elm-analyse

elm-ts:
	yarn elm-typescript-interop

elm-make-all:
	elm make src/Investor.elm src/Admin.elm  src/Public.elm

test:
	yarn elm-test

build-dev:
	yarn  webpack --config webpack.dev.js --progress --reporter=basic

build-prod:
	NODE_ENV=production yarn webpack --config webpack.prod.js --progress

start:
	yarn webpack-dev-server --config ./webpack.dev.js --hot

open-stats:
	yarn webpack-bundle-analyzer dist/app/stats.json
