graph:
	just graph-app
	just graph-pub

graph-app:
	yarn elm-graphql $API_HOST/graphql-app --base Api \
		--header "Authorization: Bearer $SYSTEM_JWT"

graph-pub:
	yarn elm-graphql $API_HOST/graphql-pub --base ApiPub

elm-analyse:
	yarn elm-analyse

elm-ts:
	yarn elm-typescript-interop

test:
	yarn elm-test

build-dev:
	npx webpack --config webpack.dev.js --progress --reporter=basic

build-prod:
	NODE_ENV=production npx webpack --config webpack.prod.js --progress

start:
	npx webpack-dev-server --config ./webpack.dev.js --hot

