build:
  docker run \
    --rm \
    -it \
    -v $PWD:/volume \
    -v cargo-cache:/root/.cargo \
    clux/muslrust:nightly \
    cargo build --release --out-dir /volume/bin -Z unstable-options

test:
  curl \
    --request POST \
    --header "Content-Type: application/json" \
    --data '{__schema{types{name}}}' \
    http://127.0.0.1:4010/graphql
