-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ApiPub.Mutation exposing (ConfirmEmailRequiredArguments, RedeemInvitationRequiredArguments, RequestPasswordResetRequiredArguments, ResetPasswordRequiredArguments, SignInRequiredArguments, SignUpRequiredArguments, confirmEmail, redeemInvitation, requestPasswordReset, resetPassword, signIn, signUp)

import ApiPub.InputObject
import ApiPub.Interface
import ApiPub.Object
import ApiPub.Scalar
import ApiPub.ScalarCodecs
import ApiPub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias SignUpRequiredArguments =
    { signUp : ApiPub.InputObject.SignUp }


signUp : SignUpRequiredArguments -> SelectionSet decodesTo ApiPub.Object.SignUpResponse -> SelectionSet decodesTo RootMutation
signUp requiredArgs object_ =
    Object.selectionForCompositeField "signUp" [ Argument.required "signUp" requiredArgs.signUp ApiPub.InputObject.encodeSignUp ] object_ identity


type alias SignInRequiredArguments =
    { signIn : ApiPub.InputObject.SignIn }


signIn : SignInRequiredArguments -> SelectionSet decodesTo ApiPub.Object.SignInResponse -> SelectionSet decodesTo RootMutation
signIn requiredArgs object_ =
    Object.selectionForCompositeField "signIn" [ Argument.required "signIn" requiredArgs.signIn ApiPub.InputObject.encodeSignIn ] object_ identity


type alias ConfirmEmailRequiredArguments =
    { input : ApiPub.InputObject.ConfirmEmailInput }


confirmEmail : ConfirmEmailRequiredArguments -> SelectionSet decodesTo ApiPub.Object.ConfirmEmailResponse -> SelectionSet decodesTo RootMutation
confirmEmail requiredArgs object_ =
    Object.selectionForCompositeField "confirmEmail" [ Argument.required "input" requiredArgs.input ApiPub.InputObject.encodeConfirmEmailInput ] object_ identity


type alias RedeemInvitationRequiredArguments =
    { input : ApiPub.InputObject.RedeemInvitationInput }


redeemInvitation : RedeemInvitationRequiredArguments -> SelectionSet decodesTo ApiPub.Object.RedeemInvitationResponse -> SelectionSet decodesTo RootMutation
redeemInvitation requiredArgs object_ =
    Object.selectionForCompositeField "redeemInvitation" [ Argument.required "input" requiredArgs.input ApiPub.InputObject.encodeRedeemInvitationInput ] object_ identity


type alias RequestPasswordResetRequiredArguments =
    { input : ApiPub.InputObject.RequestPasswordResetInput }


requestPasswordReset : RequestPasswordResetRequiredArguments -> SelectionSet decodesTo ApiPub.Object.RequestPasswordResetResponse -> SelectionSet decodesTo RootMutation
requestPasswordReset requiredArgs object_ =
    Object.selectionForCompositeField "requestPasswordReset" [ Argument.required "input" requiredArgs.input ApiPub.InputObject.encodeRequestPasswordResetInput ] object_ identity


type alias ResetPasswordRequiredArguments =
    { input : ApiPub.InputObject.ResetPasswordInput }


resetPassword : ResetPasswordRequiredArguments -> SelectionSet decodesTo ApiPub.Object.ResetPasswordResponse -> SelectionSet decodesTo RootMutation
resetPassword requiredArgs object_ =
    Object.selectionForCompositeField "resetPassword" [ Argument.required "input" requiredArgs.input ApiPub.InputObject.encodeResetPasswordInput ] object_ identity
