-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ApiPub.Object exposing (..)


type MutationError
    = MutationError


type SignInResponse
    = SignInResponse


type SignUpResponse
    = SignUpResponse
