-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ApiPub.Object exposing (ConfirmEmailResponse(..), MutationError(..), RedeemInvitationResponse(..), RequestPasswordResetResponse(..), ResetPasswordResponse(..), SignInResponse(..), SignUpResponse(..))


type ConfirmEmailResponse
    = ConfirmEmailResponse


type MutationError
    = MutationError


type RedeemInvitationResponse
    = RedeemInvitationResponse


type RequestPasswordResetResponse
    = RequestPasswordResetResponse


type ResetPasswordResponse
    = ResetPasswordResponse


type SignInResponse
    = SignInResponse


type SignUpResponse
    = SignUpResponse
