-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ApiPub.Object exposing (ConfirmEmailResponse(..), MutationError(..), RedeemInvitationResponse(..), SignInResponse(..), SignUpResponse(..), User(..))


type ConfirmEmailResponse
    = ConfirmEmailResponse


type MutationError
    = MutationError


type RedeemInvitationResponse
    = RedeemInvitationResponse


type SignInResponse
    = SignInResponse


type SignUpResponse
    = SignUpResponse


type User
    = User
