build:
	esy build

# http://localhost:8080/graphql
start: build
	esy x SaveUpApi.exe

try:
	curl -X POST \
		--data '{ "query": "{ admin { investors { name } } }" }' \
		--header "Content-Type: application/json" \
		http://127.0.0.1:8080/graphql

deploy:
	now --public

docker-build:
	docker build . -t save-up

docker-sh:
	docker run -it save-up /bin/sh
