-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Client(..), InvitationResponse(..), MutationError(..), User(..))


type Client
    = Client


type InvitationResponse
    = InvitationResponse


type MutationError
    = MutationError


type User
    = User
