-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Account(..), Admin(..), CreateUserResonse(..), DepositResponse(..), Investor(..), InvitationResponse(..), MutationError(..), RequestWithdrawalResponse(..), ResolveTransactionRequestResponse(..), Transaction(..), TransactionRequest(..), User(..), WithdrawalResponse(..))


type Account
    = Account


type Admin
    = Admin


type CreateUserResonse
    = CreateUserResonse


type DepositResponse
    = DepositResponse


type Investor
    = Investor


type InvitationResponse
    = InvitationResponse


type MutationError
    = MutationError


type RequestWithdrawalResponse
    = RequestWithdrawalResponse


type ResolveTransactionRequestResponse
    = ResolveTransactionRequestResponse


type Transaction
    = Transaction


type TransactionRequest
    = TransactionRequest


type User
    = User


type WithdrawalResponse
    = WithdrawalResponse
