-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (admin, apiVersion, investor, timezones)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


apiVersion : SelectionSet String RootQuery
apiVersion =
    Object.selectionForField "String" "apiVersion" [] Decode.string


admin : SelectionSet decodesTo Api.Object.Admin -> SelectionSet decodesTo RootQuery
admin object_ =
    Object.selectionForCompositeField "admin" [] object_ identity


investor : SelectionSet decodesTo Api.Object.Investor -> SelectionSet decodesTo RootQuery
investor object_ =
    Object.selectionForCompositeField "investor" [] object_ identity


timezones : SelectionSet (List String) RootQuery
timezones =
    Object.selectionForField "(List String)" "timezones" [] (Decode.string |> Decode.list)
