-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (NaiveDateTime, codecs)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias NaiveDateTime =
    Api.Scalar.NaiveDateTime


codecs : Api.Scalar.Codecs NaiveDateTime
codecs =
    Api.Scalar.defineCodecs
        { codecNaiveDateTime = defaultCodecs.codecNaiveDateTime
        }
