-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ApiPub.Object.MutationError exposing (key, messages)

import ApiPub.InputObject
import ApiPub.Interface
import ApiPub.Object
import ApiPub.Scalar
import ApiPub.ScalarCodecs
import ApiPub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


key : SelectionSet String ApiPub.Object.MutationError
key =
    Object.selectionForField "String" "key" [] Decode.string


messages : SelectionSet (List String) ApiPub.Object.MutationError
messages =
    Object.selectionForField "(List String)" "messages" [] (Decode.string |> Decode.list)
