-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ApiPub.Object.ResetPasswordResponse exposing (errors, jwt, success)

import ApiPub.InputObject
import ApiPub.Interface
import ApiPub.Object
import ApiPub.Scalar
import ApiPub.ScalarCodecs
import ApiPub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


success : SelectionSet Bool ApiPub.Object.ResetPasswordResponse
success =
    Object.selectionForField "Bool" "success" [] Decode.bool


errors : SelectionSet decodesTo ApiPub.Object.MutationError -> SelectionSet (List decodesTo) ApiPub.Object.ResetPasswordResponse
errors object_ =
    Object.selectionForCompositeField "errors" [] object_ (identity >> Decode.list)


jwt : SelectionSet (Maybe String) ApiPub.Object.ResetPasswordResponse
jwt =
    Object.selectionForField "(Maybe String)" "jwt" [] (Decode.string |> Decode.nullable)
