-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ApiPub.Object.User exposing (clientId, createdAt, email, emailConfirmationToken, emailConfirmedAt, id, name, passwordHash, role, selection)

import ApiPub.Enum.Role
import ApiPub.InputObject
import ApiPub.Interface
import ApiPub.Object
import ApiPub.Scalar
import ApiPub.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) ApiPub.Object.User
selection constructor =
    Object.selection constructor


id : Field Int ApiPub.Object.User
id =
    Object.fieldDecoder "id" [] Decode.int


createdAt : Field ApiPub.Scalar.NaiveDateTime ApiPub.Object.User
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map Debug.toString, Decode.int |> Decode.map Debug.toString, Decode.bool |> Decode.map Debug.toString ] |> Decode.map ApiPub.Scalar.NaiveDateTime)


clientId : Field Int ApiPub.Object.User
clientId =
    Object.fieldDecoder "clientId" [] Decode.int


email : Field String ApiPub.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


passwordHash : Field String ApiPub.Object.User
passwordHash =
    Object.fieldDecoder "passwordHash" [] Decode.string


name : Field String ApiPub.Object.User
name =
    Object.fieldDecoder "name" [] Decode.string


role : Field ApiPub.Enum.Role.Role ApiPub.Object.User
role =
    Object.fieldDecoder "role" [] ApiPub.Enum.Role.decoder


emailConfirmationToken : Field (Maybe String) ApiPub.Object.User
emailConfirmationToken =
    Object.fieldDecoder "emailConfirmationToken" [] (Decode.string |> Decode.nullable)


emailConfirmedAt : Field (Maybe ApiPub.Scalar.NaiveDateTime) ApiPub.Object.User
emailConfirmedAt =
    Object.fieldDecoder "emailConfirmedAt" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map Debug.toString, Decode.int |> Decode.map Debug.toString, Decode.bool |> Decode.map Debug.toString ] |> Decode.map ApiPub.Scalar.NaiveDateTime |> Decode.nullable)
