build:
	docker run \
		--rm \
		-it \
		-v $PWD:/volume \
		-v cargo-cache:/root/.cargo \
		clux/muslrust:stable \
		cargo build --release
	mkdir -p ../bin/hello/
	cp target/x86_64-unknown-linux-musl/release/hello ../bin/hello/
