dp-setup:
	DATABASE_URL=$DATABASE_URL_LOCAL diesel setup

db-gen name:
	diesel migration generate {{name}}

db-up:
	DATABASE_URL=$DATABASE_URL_LOCAL diesel migration run

db-down:
	DATABASE_URL=$DATABASE_URL_LOCAL diesel migration revert

dp-test-setup:
	DATABASE_URL=$DATABASE_URL_TEST diesel setup

db-test-down:
	DATABASE_URL=$DATABASE_URL_TEST diesel migration revert

db-test-up:
	DATABASE_URL=$DATABASE_URL_TEST diesel migration run

schema:
	DATABASE_URL=$DATABASE_URL_LOCAL diesel print-schema > src/models/schema.rs

build:
	docker run \
		--rm \
		-it \
		-v $PWD:/volume \
		-v cargo-cache:/root/.cargo \
		clux/muslrust:stable \
		cargo build --release
	mkdir -p ../bin/
	cp target/x86_64-unknown-linux-musl/release/graphql ../bin/
	cp target/x86_64-unknown-linux-musl/release/migrate ../bin/
