-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.InvitationResponse exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.InvitationResponse
selection constructor =
    Object.selection constructor


success : Field Bool Api.Object.InvitationResponse
success =
    Object.fieldDecoder "success" [] Decode.bool


errors : SelectionSet decodesTo Api.Object.MutationError -> Field (List decodesTo) Api.Object.InvitationResponse
errors object =
    Object.selectionField "errors" [] object (identity >> Decode.list)
