-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RequestWithdrawalResponse exposing (errors, success, transactionRequest)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


success : SelectionSet Bool Api.Object.RequestWithdrawalResponse
success =
    Object.selectionForField "Bool" "success" [] Decode.bool


errors : SelectionSet decodesTo Api.Object.MutationError -> SelectionSet (List decodesTo) Api.Object.RequestWithdrawalResponse
errors object_ =
    Object.selectionForCompositeField "errors" [] object_ (identity >> Decode.list)


transactionRequest : SelectionSet decodesTo Api.Object.TransactionRequest -> SelectionSet (Maybe decodesTo) Api.Object.RequestWithdrawalResponse
transactionRequest object_ =
    Object.selectionForCompositeField "transactionRequest" [] object_ (identity >> Decode.nullable)
