-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.TransactionRequest exposing (account, accountId, amountInCents, createdAt, id, kind, state)

import Api.Enum.TransactionKind
import Api.Enum.TransactionRequestState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.TransactionRequest
id =
    Object.selectionForField "Int" "id" [] Decode.int


createdAt : SelectionSet Api.ScalarCodecs.NaiveDateTime Api.Object.TransactionRequest
createdAt =
    Object.selectionForField "ScalarCodecs.NaiveDateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder)


accountId : SelectionSet Int Api.Object.TransactionRequest
accountId =
    Object.selectionForField "Int" "accountId" [] Decode.int


account : SelectionSet decodesTo Api.Object.Account -> SelectionSet decodesTo Api.Object.TransactionRequest
account object_ =
    Object.selectionForCompositeField "account" [] object_ identity


kind : SelectionSet Api.Enum.TransactionKind.TransactionKind Api.Object.TransactionRequest
kind =
    Object.selectionForField "Enum.TransactionKind.TransactionKind" "kind" [] Api.Enum.TransactionKind.decoder


amountInCents : SelectionSet Float Api.Object.TransactionRequest
amountInCents =
    Object.selectionForField "Float" "amountInCents" [] Decode.float


state : SelectionSet Api.Enum.TransactionRequestState.TransactionRequestState Api.Object.TransactionRequest
state =
    Object.selectionForField "Enum.TransactionRequestState.TransactionRequestState" "state" [] Api.Enum.TransactionRequestState.decoder
