-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.TransactionRequest exposing (account, accountId, amountInCents, createdAt, id, kind, selection, state)

import Api.Enum.TransactionKind
import Api.Enum.TransactionRequestState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.TransactionRequest
selection constructor =
    Object.selection constructor


id : Field Int Api.Object.TransactionRequest
id =
    Object.fieldDecoder "id" [] Decode.int


createdAt : Field Api.Scalar.NaiveDateTime Api.Object.TransactionRequest
createdAt =
    Object.fieldDecoder "createdAt" [] (Object.scalarDecoder |> Decode.map Api.Scalar.NaiveDateTime)


accountId : Field Int Api.Object.TransactionRequest
accountId =
    Object.fieldDecoder "accountId" [] Decode.int


account : SelectionSet decodesTo Api.Object.Account -> Field decodesTo Api.Object.TransactionRequest
account object_ =
    Object.selectionField "account" [] object_ identity


kind : Field Api.Enum.TransactionKind.TransactionKind Api.Object.TransactionRequest
kind =
    Object.fieldDecoder "kind" [] Api.Enum.TransactionKind.decoder


amountInCents : Field Float Api.Object.TransactionRequest
amountInCents =
    Object.fieldDecoder "amountInCents" [] Decode.float


state : Field Api.Enum.TransactionRequestState.TransactionRequestState Api.Object.TransactionRequest
state =
    Object.fieldDecoder "state" [] Api.Enum.TransactionRequestState.decoder
