-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Transaction exposing (accountId, amount, balance, createdAt, id, kind, selection)

import Api.Enum.TransactionKind
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Transaction
selection constructor =
    Object.selection constructor


id : Field Int Api.Object.Transaction
id =
    Object.fieldDecoder "id" [] Decode.int


createdAt : Field Api.Scalar.NaiveDateTime Api.Object.Transaction
createdAt =
    Object.fieldDecoder "createdAt" [] (Object.scalarDecoder |> Decode.map Api.Scalar.NaiveDateTime)


accountId : Field Int Api.Object.Transaction
accountId =
    Object.fieldDecoder "accountId" [] Decode.int


kind : Field Api.Enum.TransactionKind.TransactionKind Api.Object.Transaction
kind =
    Object.fieldDecoder "kind" [] Api.Enum.TransactionKind.decoder


amount : Field Api.Scalar.Cents Api.Object.Transaction
amount =
    Object.fieldDecoder "amount" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Cents)


balance : Field Api.Scalar.Cents Api.Object.Transaction
balance =
    Object.fieldDecoder "balance" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Cents)
