-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.UnarchiveUserResponse exposing (errors, selection, success)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.UnarchiveUserResponse
selection constructor =
    Object.selection constructor


success : Field Bool Api.Object.UnarchiveUserResponse
success =
    Object.fieldDecoder "success" [] Decode.bool


errors : SelectionSet decodesTo Api.Object.MutationError -> Field (List decodesTo) Api.Object.UnarchiveUserResponse
errors object_ =
    Object.selectionField "errors" [] object_ (identity >> Decode.list)
