-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.User exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.User
selection constructor =
    Object.selection constructor


id : Field Int Api.Object.User
id =
    Object.fieldDecoder "id" [] Decode.int


clientId : Field Int Api.Object.User
clientId =
    Object.fieldDecoder "clientId" [] Decode.int


role : Field String Api.Object.User
role =
    Object.fieldDecoder "role" [] Decode.string


name : Field String Api.Object.User
name =
    Object.fieldDecoder "name" [] Decode.string


email : Field String Api.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


passwordHash : Field String Api.Object.User
passwordHash =
    Object.fieldDecoder "passwordHash" [] Decode.string


timezone : Field String Api.Object.User
timezone =
    Object.fieldDecoder "timezone" [] Decode.string
