-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (accounts, email, id, isArchived, name, username)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.User
id =
    Object.selectionForField "Int" "id" [] Decode.int


email : SelectionSet (Maybe String) Api.Object.User
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


name : SelectionSet String Api.Object.User
name =
    Object.selectionForField "String" "name" [] Decode.string


isArchived : SelectionSet Bool Api.Object.User
isArchived =
    Object.selectionForField "Bool" "isArchived" [] Decode.bool


username : SelectionSet String Api.Object.User
username =
    Object.selectionForField "String" "username" [] Decode.string


accounts : SelectionSet decodesTo Api.Object.Account -> SelectionSet (List decodesTo) Api.Object.User
accounts object_ =
    Object.selectionForCompositeField "accounts" [] object_ (identity >> Decode.list)
