-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.WithdrawalResponse exposing (errors, success, transaction)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


success : SelectionSet Bool Api.Object.WithdrawalResponse
success =
    Object.selectionForField "Bool" "success" [] Decode.bool


errors : SelectionSet decodesTo Api.Object.MutationError -> SelectionSet (List decodesTo) Api.Object.WithdrawalResponse
errors object_ =
    Object.selectionForCompositeField "errors" [] object_ (identity >> Decode.list)


transaction : SelectionSet decodesTo Api.Object.Transaction -> SelectionSet (Maybe decodesTo) Api.Object.WithdrawalResponse
transaction object_ =
    Object.selectionForCompositeField "transaction" [] object_ (identity >> Decode.nullable)
