require "capistrano/env_config"

# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
# require "capistrano/scm/git"
# install_plugin Capistrano::SCM::Git
require 'capistrano/scm/none'
install_plugin Capistrano::Scm::None::Plugin

# Load custom tasks from `lib/capistrano/tasks`
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
