FROM rustlang/rust:nightly

ENV APP_DIR /usr/src/kic


# RUN dpkg -i $APP_GET
# RUN app install musl-dev
RUN rustup target add x86_64-unknown-linux-musl


# Create blank project
RUN USER=root cargo new $APP_DIR

# We want dependencies cached, so copy those first.
WORKDIR $APP_DIR
COPY Cargo.toml Cargo.lock $APP_DIR/

# This is a dummy build to get the dependencies cached.
RUN cargo build --release
