FROM clux/muslrust:stable

WORKDIR /volume

COPY ./shared/Cargo.toml ./shared/Cargo.toml
COPY ./shared/Cargo.lock ./shared/Cargo.lock
COPY ./shared/src ./shared/src

COPY ./mail/Cargo.toml ./mail/Cargo.toml
COPY ./mail/Cargo.lock ./mail/Cargo.lock
COPY ./mail/src ./mail/src
COPY ./mail/templates ./mail/templates

