FROM clux/muslrust:stable

WORKDIR /volume

COPY ./shared/Cargo.toml ./shared/Cargo.toml
COPY ./shared/Cargo.lock ./shared/Cargo.lock
COPY ./shared/src ./shared/src

COPY ./graphql/Cargo.toml ./graphql/Cargo.toml
COPY ./graphql/Cargo.lock ./graphql/Cargo.lock
COPY ./graphql/diesel.toml ./graphql/diesel.toml
COPY ./graphql/migrations ./graphql/migrations
COPY ./graphql/src ./graphql/src

WORKDIR /volume/graphql
