FROM rustlang/rust:nightly

ENV APP_DIR /usr/src/kic

# Create blank project
RUN USER=root cargo new $APP_DIR

# We want dependencies cached, so copy those first.
WORKDIR $APP_DIR
COPY Cargo.toml Cargo.lock $APP_DIR/

# This is a dummy build to get the dependencies cached.
RUN cargo build --release

# Now copy in the rest of the sources
# COPY src $APP_DIR/src/

# Actual build.
# RUN cargo build --release
