# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem "capistrano", "~> 3.11", require: false
  gem "capistrano-scm-none", "~> 0.1"
  gem "capistrano-env_config"
end
