start:
	DATABASE_URL=$DATABASE_URL sam local start-api -p 4010 --skip-pull-image

build:
	just hello/build
	just graphql/build

# Generate SAM template.yml, so we can test this locally
gen-sam:
	sls sam export --output ./template.yml

try:
	curl \
		--request POST \
		--header "Content-Type: application/json" \
		--data '{"query": "{__schema{types{name}}}", "variables": {}, "operationName": null}' \
		http://127.0.0.1:4010/graphql

# Didn't work yet
sam-try-mail:
	sam local invoke "Mail" --event mail/src/fixtures/sns-event-invite.json

# Didn't work yet
sls-try-mail:
	sls invoke -f mail --path mail/src/fixtures/sns-event-invite.json

invoke-migration:
	curl \
		--request POST \
		http://127.0.0.1:4010/migrate

# package:
# 	sam package \
# 		--template-file template.yaml \
# 		--s3-bucket kic-api \
# 		--output-template-file packaged.yaml

# deploy:
# 	sam deploy \
# 		--template-file ./packaged.yaml \
# 		--stack-name kic-api \
# 		--capabilities CAPABILITY_IAM

deploy:
	sls deploy
