up:
  diesel migration run

up-test:
  DATABASE_URL=$DATABASE_URL_TEST diesel migration run

setup-test:
  DATABASE_URL=$DATABASE_URL_TEST diesel setup

schema:
  diesel print-schema > src/models/schema.rs

build:
  cargo build

build-release:
  docker build \
    -f Dockerfile.release \
    -t kic-api .

  docker run \
    -it -v "$(pwd):/usr/src/kic" kic-api \
    cargo build --release --target=x86_64-unknown-linux-gnu

  cp ./target/x86_64-unknown-linux-gnu/release/api ./release/api


run: build
  cargo run

start:
  cargo watch -x run

test:
  APP_ENV=test cargo test

