up:
  diesel migration run

up-test:
  DATABASE_URL=$DATABASE_URL_TEST diesel migration run

setup-test:
  DATABASE_URL=$DATABASE_URL_TEST diesel setup

schema:
  diesel print-schema > src/models/schema.rs

build:
  cargo build

deploy:
  deploy.sh

# Shell into the Docker release container
sh:
  docker run -i -t --entrypoint /bin/bash kic-api

run: build
  cargo run

start:
  cargo watch -x run

test:
  APP_ENV=test cargo test

